### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gitRamil** [Redestros/ApiGateway#4]
On the step from README terraform appy I get an error:
│ Error: error initializing keycloak provider
│
│   with provider["registry.terraform.io/mrparkers/keycloak"],
│   on main.tf line 10, in provider "keycloak":
│   10: provider "keycloak" {
│
│ failed to perform initial login to Keycloak: error sending POST request to
│ http://localhost:8080/realms/master/protocol/openid-connect/token: 401 Unauthorized
Please tell me how I can fix this error?

**Comment by Redestros** [comment]
Hi @gitRamil , did you run the create-terraform-client.sh script ?

**Comment by gitRamil** [comment]
@Redestros You were right, script  create-terraform-client.sh did not execute correctly.
I encountered a number of problems:
1) C:\ApiGateway\infra>bash create-terraform-client.sh
```
create-terraform-client.sh: line 2: $'\r': command not found
create-terraform-client.sh: line 8: $'\r': command not found
Creating initial terraform client
create-terraform-client.sh: line 10: $'\r': command not found
create-terraform-client.sh: command substitution: line 27: syntax error near unexpected token `|'
'reate-terraform-client.sh: command substitution: line 27: ` | jq -r '.access_token'
create-terraform-client.sh: line 20: $'\r': command not found
create-terraform-client.sh: line 21: syntax error near unexpected token `$'{\r''
'reate-terraform-client.sh: line 21: `function post() {
```
Fixed by changing line ending characters
2) C:\ApiGateway\infra>bash create-terraform-client.sh
```
Creating initial terraform client
./create-terraform-client.sh: line 20: jq: command not found
./create-terraform-client.sh: line 54: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   121    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
./create-terraform-client.sh: line 64: jq: command not found
./create-terraform-client.sh: line 65: jq: command not found
./create-terraform-client.sh: line 68: jq: command not found
./create-terraform-client.sh: line 77: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   121    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
Extending access token lifespan (don't do this in production)
./create-terraform-client.sh: line 96: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   121    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
Done
```
Fixed by installing jq
3) Also after all the actions when following the link https://localhost:7140/weatherforecast I received an error `net::ERR_CERT_INVALID localhost fix error`. Fixed by enabling allow-insecure-localhost in Chrome. 
The application was launched successfully, thank you very much for your help and example!

**Comment by Redestros** [comment]
You're welcome! I'm glad to hear everything is running successfully. If you have any more questions or need further assistance, feel free to reach out.
